// import ReduxProvider from "@/providers/ReduxProvider";
// import "./globals.css";
// import { Figtree, Fredoka } from "next/font/google";
// import NextTopLoader from "nextjs-toploader";
// import Provider from "@/providers/Provider";
// import { Toaster } from "sonner";
// import AuthProvider from "@/providers/AuthProvider";

// const figtree = Figtree({
//   subsets: ["latin"],
//   variable: "--font-figtree",
// });
// const fredoka = Fredoka({
//   subsets: ["latin"],
//   variable: "--font-fredoka",
// });

// export const metadata = {
//   title: "Fofood",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${figtree.variable} ${fredoka.variable}`}>
//         <NextTopLoader color="#DB6885" height={5} />
//         <ReduxProvider>
//           {" "}
//           <Provider>
//             <Toaster></Toaster>
//             <AuthProvider>{children}</AuthProvider>
//           </Provider>
//         </ReduxProvider>
//       </body>
//     </html>
//   );
// }

import DashBoardNavbar from "@/components/dashboard-navbar";
import Menu from "@/components/Menu";

import Image from "next/image";
import Link from "next/link";

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen flex">
      {/* LEFT */}
      <div className="w-[14%] md:w-[8%] lg:w-[16%] xl:w-[14%] p-4">
        <Link
          href="/"
          className="flex items-center justify-center lg:justify-start gap-2"
        >
          <Image src="/logo.png" alt="logo" width={32} height={32} />
          <span className="hidden lg:block font-bold">SchooLama</span>
        </Link>
        <Menu />
      </div>
      {/* RIGHT */}
      <div className="w-[86%] md:w-[92%] lg:w-[84%] xl:w-[86%] bg-[#F7F8FA] overflow-scroll flex flex-col">
        <DashBoardNavbar />
        {children}
      </div>
    </div>
  );
}
