import ReduxProvider from "@/providers/ReduxProvider";
import "./globals.css";
import { Figtree, Fredoka } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import Provider from "@/providers/Provider";
import { Toaster } from "sonner";
import AuthProvider from "@/providers/AuthProvider";

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
});
const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
});

export const metadata = {
  title: "Fofood",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} ${fredoka.variable}`}>
        <NextTopLoader color="#DB6885" height={5} />
        <ReduxProvider>
          {" "}
          <Provider>
            <Toaster></Toaster>
            <AuthProvider>{children}</AuthProvider>
          </Provider>
        </ReduxProvider>
      </body>
    </html>
  );
}
