import Navbar from "@/components/navbar";
import "./globals.css";
import { Figtree, Fredoka } from "next/font/google";
import Footer from "@/components/footer";
import NextTopLoader from "nextjs-toploader";

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
});
const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
});

export const metadata = {
  title: "Fofood",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} ${fredoka.variable}`}>
        <NextTopLoader color="#DB6885" height={5} />
        {children}
      </body>
    </html>
  );
}
